#!/bin/sh
#$ -cwd

# 実行環境を指定
#$ -l f_node=5
# 実行時間を指定
#$ -l h_rt=16:00:00
#$ -N serial

# moduleコマンドの初期化
. /etc/profile.d/modules.sh
# 各種環境の読み込み
module load cuda
module load openmpi
module load papi
module load gcc
# 実行
../execBenchmarkExcludeBTSPonF.sh 128 28
