#!/bin/sh
#$ -cwd

# 実行環境を指定
#$ -l q_core=2
# 実行時間を指定
#$ -l h_rt=4:00:00
#$ -N serial

# moduleコマンドの初期化
. /etc/profile.d/modules.sh
# 各種環境の読み込み
module load cuda
module load openmpi
module load papi
module load gcc
# 実行
../execBenchmarkExcludeBTSPonW.sh 8 4
