#!/bin/sh
# カレントディレクトリでジョブを実行する
#$ -cwd

# 資源タイプC1 1ノードを使用
#$ -l s_core=1
# 実行時間を指定
#$ -l h_rt=0:05:00
#$ -N serial

# Moduleコマンドの初期化
. /etc/profile.d/modules.sh
# CUDA環境の読込
module load cuda/8.0.61
# OpenMPI環境の読込
module load openmpi/2.1.2
# Score-P環境の読み込み
module load scorep
# gcc環境の読み込み
module load gcc

# 実行
## ノード当たり1プロセス MPI全1プロセス を使用
mpirun -npernode 1 -n 1 bt.S.x

