#!/bin/sh
# カレントディレクトリでジョブを実行する
#$ -cwd

# ノード毎プロセス数1
A=1
# 合計プロセス数1
B=1

# 資源タイプC4 1ノードを使用
#$ -l q_core=1
# 実行時間を指定
#$ -l h_rt=0:09:30

# Moduleコマンドの初期化
. /etc/profile.d/modules.sh
# CUDA環境の読込
module load cuda
# OpenMPI環境の読込
module load openmpi
# PAPI環境の読み込み
module load papi
# gcc環境の読み込み
module load gcc

export PATH="$PATH:/home/9/20IA1328/tau-2.29/x86_64/bin"
export TAU_MAKEFILE=/home/9/20IA1328/tau-2.29/x86_64/lib/Makefile.tau-papi-mpi-pdt
export TAU_OPTIONS=-optRevert
export PATH="$PATH:/home/9/20IA1328/pdtoolkit-3.25.1/x86_64//bin"

# 実行
# ノードあたりAプロセスMPI全B プロセスを使用
mpirun -npernode $A -n $B -x LD_LIBRARY_PATH lu.D.x

